title: zhy # 站点标题
url: https://zhy-2020.github.io/ # 你的域名，例如 https://wu-kan.github.io
baseurl: "" # 假如你的博客是建在某个目录下的，请在这里加上目录名，并且下面配置的所有链接里的`/assets`前也要加，即`/your_baseurl/assets`。这一项结尾不要有'/'。

defaults: # 将所有配置选项使用<https://jekyllrb.com/docs/configuration/front-matter-defaults/>功能进行配置
  - scope:
      path: "" # an empty string here means all files in the project
    values: # 以下配置项也可以在任意页面自定义
      categories: "_posts"
      jekyll-theme-WuK: # 我的主题的自定义样式都在这个命名空间
        default:
          body:
            theme-base: theme-base-07 # 可选的主题色包括08~0f，见 <https://github.com/poole/lanyon>
            layout-reverse: true # 开启后sidebar在右边，反之左边
            sidebar-overlay: true # 开启后正文不随sidebar移动而移动
          append_to_head: # 通过内嵌html的方式引入并定制插件，删改前确定知道自己在做什么。定制插件的方式可以参考这篇文章 <https://wu-kan.cn/_posts/2019-01-18-基于Jekyll搭建个人博客/>
            - | #一些页面优化标签，看不懂可跳过
              <meta
                name="viewport"
                content="width=device-width,minimum-scale=1,initial-scale=1"
              />
              <meta
                http-equiv="content-type"
                content="text/html; charset=utf-8"
              />
              <link
                rel="alternate"
                href="/feed.xml"
                title="RSS"
                type="application/rss+xml"
              />
            - | # 网站小图标，可换成你自己的图片，改href中的部分即可
              <link
                rel="apple-touch-icon-precomposed"
                href="https://gravatar.loli.net/avatar/289efba375d63424de3c49569c446744?s=320"
              />
              <link
                rel="shortcut
                icon"
                href="https://gravatar.loli.net/avatar/289efba375d63424de3c49569c446744?s=32"
              />
            - | # 来自lanyon的页面样式，不要改
              <link
                rel="stylesheet"
                href="https://cdn.jsdelivr.net/combine/gh/poole/lanyon@v1.1.0/public/css/poole.min.css,gh/poole/lanyon@v1.1.0/public/css/lanyon.min.css,gh/poole/lanyon@v1.1.0/public/css/syntax.min.css"
              />
            - | # 用js引入fontawesome图标样式，功能更丰富
              <script
                async="async"
                src="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.1/js/all.min.js"
              ></script>
            - | # 百度爬虫推送，http站点使用 http://push.zhanzhang.baidu.com/push.js
              <script
                src='https://zz.bdstatic.com/linksubmit/push.js'
                async="async"
              ></script>
            - | # 网站背景图片，分竖屏、宽屏；改链接即可，不想用可以把这一项全删掉；要换壁纸图片的话可把url内的部分换成你自己的，比如你放在 /assets/image/background.jpg，那就改成 url(/assets/image/background.jpg)
              <style>
                .wrap {
                  transition-property: width,background-size,transform;
                  transition-duration: .3s;
                  transition-timing-function: ease-in-out;
                  min-height: 100%;
                  display: inline-block;
                  background-size: 100% auto;
                  background-position: 0% 0%;
                  background-repeat: no-repeat;
                  background-attachment: fixed;
                  background-image: url(https://Mizuno-Ai.wu-kan.cn/pixiv/74559485_p1.webp);
                }
                @media (min-aspect-ratio: 2400/1850) {
                  .wrap {
                    background-image: url(https://Mizuno-Ai.wu-kan.cn/pixiv/71932901_p0.webp);
                  }
                }
                .sidebar-overlay #sidebar-checkbox:checked ~ .wrap {
                  width: calc(100% - 14rem);
                  background-size: calc(100% - 14rem) auto;
                  transform: translateX(14rem);
                }
                .layout-reverse.sidebar-overlay #sidebar-checkbox:checked ~ .wrap {
                  transform: translateX(0);
                }
              </style>
            - | # 网站字体，要换字体建议架梯子上<https://fonts.google.com/>挑选，再通过fonts.loli.net 加速引入
              <style>
                .sidebar,
                html,
                h1,
                h2,
                h3,
                h4,
                h5,
                h6 {
                  font-family: PingFang SC, Menlo, Monaco, "Courier New", Microsoft JhengHei, monospace;
                }
              </style>
            - | # 网页标题使用加粗字号
              <style>
                h1,
                h2,
                h3,
                h4,
                h5,
                h6 {
                  font-weight: bold;
                }
              </style>
            - | #修复行内图片默认样式
              <style>
                img {
                  display: inline-block;
                  margin: 0;
                }
              </style>
            - | # 彩虹滚动条，仅对Chrome系浏览器生效
              <style>
                ::-webkit-scrollbar {
                  width: 3px;
                  height: 3px;
                }
                ::-webkit-scrollbar-thumb {
                  background-image: linear-gradient(45deg, Cyan 0%, Magenta 50%, Yellow 100%);
                }
              </style>
            - | # 选中字体颜色
              <style>
                ::selection {
                  color: White;
                  background: Black;
                }
              </style>
        page:
          masthead: # 显示顶栏
            enable: true
          katex: # katex 数学公式插件
            enable: true
            append: | # 对KaTeX过长公式渲染超出页面的修正，感谢[@AmachiInori](https://github.com/wu-kan/wu-kan.github.io/issues/13)
              <link
                rel="stylesheet"
                href="https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.css"
              />
              <style>
                .katex-display>.katex {
                  white-space: normal;
                }
              </style>
              <script
                src="https://cdn.jsdelivr.net/combine/npm/katex@0.12.0/dist/katex.min.js,npm/katex@0.12.0/dist/contrib/auto-render.min.js"
                async="async"
                onload='renderMathInElement(document.body, { delimiters: [{left: "$$", right: "$$", display: true}, { left: "$", right: "$", display: false }, {left: "\\(", right: "\\)", display: false}, {left: "\\[", right: "\\]", display: true}]})'
              ></script>
          mermaid: # mermaid图插件
            enable: true
            append: |
              <style>
                pre.language-mermaid,
                code.language-mermaid {
                  display: none;
                }
                .mermaid {
                  overflow: auto auto;
                  max-width: 100%;
                  max-height: 66.6vh;
                }
              </style>
              <script
                src="https://cdn.jsdelivr.net/npm/mermaid@8.8.4/dist/mermaid.min.js"
                async="async"
                onload='
                  for(let x of document.getElementsByClassName("language-mermaid"))
                    if(x.nodeName=="CODE")
                    {
                      let m = document.createElement("div");
                      m.classList.add("mermaid");
                      m.textContent = x.textContent;
                      x.parentNode.insertAdjacentElement("beforebegin", m);
                    }'
              ></script>
          prism: # 代码高亮插件
            enable: true
            append: |
              <link
                rel="stylesheet"
                href="https://cdn.jsdelivr.net/combine/npm/prismjs@1.22.0/plugins/line-numbers/prism-line-numbers.min.css,npm/prismjs@1.22.0/plugins/toolbar/prism-toolbar.min.css,npm/prismjs@1.22.0/plugins/match-braces/prism-match-braces.min.css,npm/prism-themes@1.4.0/themes/prism-nord.min.css"
              />
              <script
                src="https://cdn.jsdelivr.net/combine/npm/prismjs@1.22.0/components/prism-core.min.js,npm/prismjs@1.22.0/plugins/autoloader/prism-autoloader.min.js,npm/prismjs@1.22.0/plugins/line-numbers/prism-line-numbers.min.js,npm/prismjs@1.22.0/plugins/toolbar/prism-toolbar.min.js,npm/prismjs@1.22.0/plugins/match-braces/prism-match-braces.min.js"
                async="async"
                data-autoloader-path="https://cdn.jsdelivr.net/npm/prismjs@1.22.0/components/"
                onload='
                  for(let x of document.getElementsByClassName("content"))
                    x.classList.add("line-numbers","match-braces");
                  Prism.plugins.toolbar.registerButton("select-code", function (env) {
                    let button = document.createElement("button");
                    button.textContent = "select this " + env.language;
                    button.addEventListener("click", function () {
                      if (document.body.createTextRange) {
                        let range = document.body.createTextRange();
                        range.moveToElementText(env.element);
                        range.select();
                      } else if (window.getSelection) {
                        let selection = window.getSelection();
                        let range = document.createRange();
                        range.selectNodeContents(env.element);
                        selection.removeAllRanges();
                          selection.addRange(range);
                      }
                    });
                    return button;
                  })'
              ></script>
          prepend:
            - | # 代码块过长自动折叠
              <style>
                pre {
                  max-height: 66.6vh;
                  overflow: auto;
                }
              </style>
            - | # 增加宽屏下的显示内容
              <style>
                .container {
                  min-width: 66.6%;
                }
              </style>
            - | # 给文章加上磨砂背景，防止被背景影响阅读；同时加上加载动画
              <style>
                .masthead,
                .container.content {
                  padding-top: 1rem;
                  padding-bottom: 1rem;
                  margin-bottom: 1.5rem;
                  box-shadow: 0 0 .75rem rgba(0, 0, 0, 0.1);
                  background-color: rgba(255,255,255,.9);
                  animation-duration: 2s;
                  animation-name: fadeIn;
                }
                @keyframes fadeIn {
                  from {
                    opacity: 0;
                  }
                  to {
                    opacity: 1;
                  }
                }
              </style>
        home: # 展示页的配置可跳过，详见<https://revealjs.com/>
          append_to_section_tag:
            - key: data-markdown
            - key: data-separator # 水平展示页分隔符
              value: <!-- .slide -->
            - key: data-separator-vertical # 垂直展示页分隔符
              value: <!-- .slide vertical=true -->
            - key: data-background-color
              value: "White"
          prepend: |
            <link
              rel="stylesheet"
              href="https://cdn.jsdelivr.net/combine/npm/reveal.js@4.1.0/dist/reveal.min.css,npm/reveal.js@4.1.0/dist/theme/serif.min.css"
            />
            <style>
              .sidebar {
                line-height: 1.5;
              }
              .reveal .slides {
                text-align: left;
              }
              .reveal a {
                color: #268BD2;
              }
            </style>
          append: |
            <script
              async="async"
              src="https://cdn.jsdelivr.net/combine/npm/reveal.js@4.1.0/dist/reveal.min.js,npm/reveal.js@4.1.0/plugin/markdown/markdown.min.js,npm/reveal.js@4.1.0/plugin/math/math.min.js,npm/reveal.js@4.1.0/plugin/highlight/highlight.min.js"
              onload="
              for(let x of document.getElementsByClassName('wrap'))
                x.classList.add('reveal');
              Reveal.initialize({
                height: '100%',
                hash: true,
                mouseWheel: true,
                navigationMode: 'linear',
                plugins: [ RevealMarkdown,RevealMath,RevealHighlight ]
              });
            "></script>
        page404:
          prepend:
            - | # 腾讯公益
              <script
                src='https://qzonestyle.gtimg.cn/qzone/hybrid/app/404/search_children.js'
                async='async'
                charset='utf-8'
                homePageUrl='/'
                homePageName='回到我的主页'
              ></script>

compress_html: # <https://github.com/penibelst/jekyll-compress-html>
  clippings: all
  comments: [] # 注释不能压缩，否则 reveal.js 的 ppt切屏受影响
  endings: all
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []

# githubpage上支持的插件见<https://pages.github.com/versions/>
plugins: # <https://jekyllrb.com/docs/plugins/>
  - jekyll-readme-index # 使用readme做index，从而和github渲染效果一致
  - jekyll-default-layout # 为每个markdown自动生成layout
  - jekyll-seo-tag # 为每个页面生成标题
  - jekyll-sitemap # 为站点生成站点地图
  - jekyll-feed # 为站点生成RSS源
  - jekyll-remote-theme # 使用remote_theme插件实现主题的前后分离，详见<https://github.com/benbalter/jekyll-remote-theme/>

remote_theme: https://github.com/wu-kan/jekyll-theme-WuK@4.0.2 #使用固定版本号以防止主题更新导致站点显示错乱

readme_index: # 缺失index.md和index.html时，使用README.md代替之
  with_frontmatter: true # 支持带有yaml头的README

webmaster_verifications: # <https://jekyll.github.io/jekyll-seo-tag/usage/>
  google: YIKi1rBnyUaS-DMYiluseI5kZzTwjCkTFmKkSkMZDJk
  baidu: szbTSfUGAB

permalink: /:categories/:year-:month-:day-:title/ #生成文章的地址格式，我希望它和_posts目录下的格式一样
# timezone: Asia/Shanghai # 解决githubpage显示时间不正确的问题，见<https://www.iana.org/time-zones>
future: true # 允许发布时间在未来的文章

# limit_posts: 999 # 限制博文数量
# encoding: utf-8

markdown: kramdown
kramdown: # 见<https://kramdown.gettalong.org/options.html>
  input: GFM # 见<http://jekyllcn.com/docs/configuration/#kramdown>
  syntax_highlighter_opts: # 可见<https://kramdown.gettalong.org/syntax_highlighter/rouge.html>
    block:
      disable: true # 关掉代码块默认的高亮，换用prismjs
      line_numbers: false #渲染出来的效果好鬼畜
    span:
      disable: true
# 以下为 githubpage上不可修改的参数，见<https://help.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll>
#lsi: false # 为相关文章生成索引
#safe: true # 禁用自定义插件
#source: [your repo's top level directory] # Jekyll 读取文件的路径
#incremental: false # 增量生成
#highlighter: rouge # 代码高亮器
#gist:
#  noscript: false
#kramdown:
#  math_engine: mathjax
#  syntax_highlighter: rouge
